# Generated by Django 4.1.5 on 2023-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('imageUrls', models.CharField(max_length=5000)),
                ('prize', models.FloatField()),
                ('discount', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
