# Generated by Django 4.1.5 on 2023-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='imageUrls',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
