# Generated by Django 4.1.5 on 2023-01-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solid_api', '0002_alter_drinks_discount_alter_drinks_imageurls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='imageUrls',
        ),
    ]
